#
#                                      / \  //\
#    LightMine           |\___/|      /   \//  \\
#     Development        /0  0  \__  /    //  | \ \
#                       /     /  \/_/    //   |  \  \
#                       @_^_@'/   \/_   //    |   \   \
#                       //_^_/     \/_ //     |    \    \
#                    ( //) |        \///      |     \     \
#  By              ( / /) _|_ /   )  //       |      \     _\
#   Riku           ( // /) '/,_ _ _/  ( ; -.    |    _ _\.-~        .-~~~^-.
#              (( / / )) ,-{        _      `-.|.-~-.           .~         `.
#             (( // / ))  '/\      /                 ~-. _ .-~      .-~^-.  \
#             (( /// ))      `.   {            }                   /      \  \
#              (( / ))     .----~-.\        \-'                 .~         \  `. \^-.
#                         ///.----..>        \             _ -~             `.  ^-`  ^-_
#                            ///-._ _ _ _ _ _ _}^ - - - - ~                     ~-- ,.-~
#                                                                              /.-~
#
#          .              _       .    .       __         .    .   __  __               \    
#          /     `   ___. /      _/_   /       |    ___   |    |   |   |    ___    ___  |   ,
#          |     | .'   ` |,---.  |    |       |   /   `  |    |   |___|   /   ` .'   ` |  / 
#          |     | |    | |'   `  |    |  /\   /  |    |  |    |   |   |  |    | |      |-<  
#          /---/ /  `---| /    |  \__/ |,'  \,'   `.__/| /\__ /\__ /   /  `.__/|  `._.' /  \_
#                   \___/                                                                    
#             
LightWallHack:
  messages:
    noConsole: "Не для консоли, ты черт усатый."
    noPerm: "У вас недостаточно прав."
    whCount: "title:%n&7По близости было обнаружено &f%count%&7 игроков."
    notFound: "По близости игроков не обнаружено."
    cooldown: "Команда недоступна, попробуйте через %cd% сек."
    notEnoughtMoney: "title:%nНехватает деняк, лох. как у Антона) А именно: %money%"
    notGroupInGroups: "actionbar:Иди нахуй."
  groups:
    vip:
      active: 30
      radius: 30
      cooldown: 15
      cost: 500
